#![cfg_attr(not(for_host), no_std)]

#[macro_use]
extern crate alloc;

#[cfg(not(feature = "for_host"))]
pub mod bench;
pub mod ds;
pub mod convert;
pub mod constants;
#[cfg(not(feature = "for_host"))]
pub mod daisy_seed_board;
pub mod fft;
#[cfg(not(feature = "for_host"))]
pub mod fft_bench;
#[cfg(not(feature = "for_host"))]
pub mod fft_board;
#[cfg(feature = "for_host")]
pub mod fft_host;
#[cfg(feature = "for_host")]
pub mod file;
pub mod filter;
pub mod globby;
#[cfg(not(feature = "for_host"))]
pub mod globby_board;
#[cfg(feature = "for_host")]
pub mod globby_host;
#[cfg(feature = "for_host")]
pub mod graphing;
pub mod knob;
pub mod knob_dummy;
#[cfg(not(feature = "for_host"))]
pub mod knob_board;
#[cfg(feature = "for_host")]
pub mod hw_host;
#[cfg(not(feature = "for_host"))]
pub mod load_board;
#[cfg(feature = "for_host")]
pub mod load_host;
#[cfg(not(feature = "for_host"))]
pub mod mem;
pub mod r#override;
pub mod panic;
pub mod patch;
pub mod playhead;
pub mod rig;
pub mod rig_util;
#[cfg(not(feature = "for_host"))]
pub mod rig_board;
#[cfg(feature = "for_host")]
pub mod rig_host;
pub mod rig_type;
pub mod rubin;
pub mod sdram;
pub mod signal;
#[cfg(feature = "for_host")]
pub mod sim;
pub mod speed_test;
pub mod spew;
#[cfg(not(feature = "for_host"))]
pub mod spew_board;
#[cfg(feature = "for_host")]
pub mod spew_host;
pub mod static_buffer;
pub mod switch;
pub mod switch_dummy;
#[cfg(not(feature = "for_host"))]
pub mod switch_board;
pub mod test;
pub mod test_cases;
pub mod test_direct;
pub mod testdata;
#[cfg(feature = "for_host")]
pub mod testdump;
pub mod testutil;
pub mod time;
#[cfg(not(feature = "for_host"))]
pub mod time_board;
#[cfg(feature = "for_host")]
pub mod time_host;
